Repository ultralytics/autoimport, pull requests merged in 2025-01, with the labels that each got.

#1 Update README.md
  README.md
Labels: documentation, enhancement

#3 Update ci.yml
  .github/workflows/ci.yml
Labels: enhancement

#2 Update pyproject.toml
  .gitignore
  autoimport/README.md
  autoimport/__init__.py
  autoimport/module1.py
  pyproject.toml
  tests/test_module1.py
Labels: dependencies, documentation, enhancement

#5 Update code and add tests
  .github/workflows/ci.yml
  autoimport/__init__.py
  autoimport/main.py
  autoimport/module1.py
  pyproject.toml
  tests/test_imports.py
  tests/test_module1.py
Labels: dependencies, documentation, enhancement

#6 Update README.md
  README.md
  tests/test_autoimport.py
Labels: documentation, enhancement

#8 Update __init__.py
  autoimport/__init__.py
Labels: dependencies, enhancement

#9 Update README.md
  README.md
Labels: documentation

#7 Update publish.yml
  autoimport/__init__.py
Labels: dependencies, enhancement

#11 Delete docs directory
  docs/README.md
Labels: documentation

#10 Add downloads badge
  README.md
Labels: documentation, enhancement

#12 Ultralytics Refactor https://ultralytics.com/actions
  autoimport/main.py
Labels: enhancement

#13 Delete autoimport/README.md
  autoimport/README.md
Labels: documentation

#14 Scope time import
  autoimport/main.py
Labels: documentation, enhancement

#15 Update pyproject.toml
  pyproject.toml
Labels: dependencies, documentation

#16 Update README.md
  README.md
Labels: documentation, enhancement

#18 Add submodule import tests
  tests/test_autoimport.py
Labels: documentation, enhancement

#19 Test multiple imports
  tests/test_autoimport.py
Labels: enhancement

#21 `v0.0.3` Return correct Type and Repr after first use
  autoimport/__init__.py
  autoimport/main.py
  tests/README.md
  tests/test_autoimport.py
Labels: enhancement
